### ISSUE TITLE
Autoreloading doesn't work when placing Rust code in root folder.

### ISSUE THREAD

**Issue by jcaesar** [wasm-tool/wasm-pack-plugin#131]
I like projects without folders, especially for smaller things. This can be done in `Cargo.toml` by
```toml
[lib]
crate-type = ["cdylib"]
path = "index.rs"
```
but that'll break `webpack serve`'s auto reloading since it just watches the `src` folder.

(Probably, implementing #66 would be enough to make this work reasonably.)
